part1: part1.cpp
	g++ part1.cpp
	./a.out sample.ppm 
part2_1a: part2_1a.cpp
	g++ part2_1a.cpp -lpthread
	./a.out sample.ppm
part2_1b: part2_1b.cpp
	g++ part2_1b.cpp -lpthread
	./a.out sample.ppm
part2_2: part2_2.cpp
	g++ part2_2.cpp -lpthread
	./a.out sample.ppm
part2_3: part2_3.cpp
	g++ part2_3.cpp -lpthread
	./a.out sample.ppm
